## Avendo lista di liste, usiamo CASTING per creare array in 'np'

In [6]:
import numpy as np  #importiamo pacchetto np per lavorare con funzioni di array

In [8]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]  #lista di liste

In [10]:
arr=np.array(mat)   #casting creando una variabile con funzione .array di 'np'

In [12]:
arr  #richiamiamo la nuova variabile e vediamo che è stampata in righe/colonne, proprio come una tabella

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Importa modulo math e prova ad usare funzioni .sin(), .cos(), .factorial(), .pi

In [14]:
import math

In [30]:
math.pi

3.141592653589793

In [35]:
math.sin

<function math.sin(x, /)>

In [37]:
math.cos

<function math.cos(x, /)>

In [39]:
math.factorial

<function math.factorial(n, /)>

## L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] trasformiamola in un array NumPy (casting): lst = np.array(lst)

In [43]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 

In [45]:
lst = np.array(lst)

### qual è stata la vendita massima mensile?

In [52]:
lst.max()

8150

### E quella minima?

In [56]:
lst.min()

1280

### quali sono le vendite mensili maggiori di 4999 oggetti?

In [77]:
filtro4999=lst>4999
lst[filtro4999]

array([5500, 7200, 6410, 8150, 7100, 5350])

### e quante ne sono?

In [79]:
lst[filtro4999].shape

(6,)

### quali sono le vendite minori di 3000 oggetti?

In [82]:
filtro3000=lst<3000
lst[filtro3000]

array([2000, 1280, 1900, 2500])

### In media quanti oggetti sono stati venduti al mese?

In [87]:
lst.mean()

4634.166666666667

## L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: import numpy as np stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: • con un ciclo for e con masking

In [96]:
stipendi=np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )

### MASKING

In [103]:
stipendi*2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

### CICLO FOR

In [124]:
for stipendio in stipendi:
    stipendio *=2

    print(stipendio)

200
400
600
800
1000
1200
1400
1600
1800
2000
